project_name: acme-register
builds:
  - main: ./cmd
    binary: acme-register
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - linux
      - darwin
    ldflags:
      - >-
        -X main.Version={{ .Tag }}
        -X main.GitCommit={{ .Commit }}
        -X main.BuildDate={{ .Date }}
archives:
  - files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
